# Generated by Django 3.2.5 on 2023-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='store',
        ),
        migrations.AddField(
            model_name='menu',
            name='store',
            field=models.ManyToManyField(to='EatApi.Store'),
        ),
    ]
