# Generated by Django 3.2.5 on 2023-03-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EatApi', '0004_auto_20230330_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='quantity',
        ),
    ]
