# Generated by Django 3.2.5 on 2023-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatApi', '0005_remove_dish_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(default=1),
        ),
    ]
