# Generated by Django 3.2.5 on 2023-03-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EatApi', '0007_auto_20230330_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
