# Generated by Django 3.2.5 on 2023-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatApi', '0009_auto_20230404_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='dish',
            field=models.IntegerField(),
        ),
    ]
